{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-postgresql-operator.fullname" . }}-role
  labels:
    {{- include "k8s-postgresql-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-postgresql-operator.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-postgresql-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

