apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.k8sServiceName }}
  labels:
    {{- include "k8s-postgresql-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-postgresql-operator.selectorLabels" . | nindent 4 }}

