apiVersion: instance.alexvyrodov.example/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  # Database is the name of the PostgreSQL database to create
  database: "mydatabase"
  
  # Owner is the PostgreSQL user that will own the database
  # This user must exist in PostgreSQL (can be created via User CRD)
  # Make sure to create the user first using the User CRD before creating the database
  owner: "myuser"
  
  # PostgresqlID is the ID of the PostgreSQL instance where this database should be created
  # This must match the postgresqlID in the Postgresql CRD
  # Example: "2BDAAA95-0465-473B-B270-E5503F1554FD"
  postgresqlID: "2BDAAA95-0465-473B-B270-E5503F1554FD"

