apiVersion: instance.alexvyrodov.example/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-sample
spec:
  # Username is the PostgreSQL username to create
  username: "myuser"
  
  # Password is the password for the PostgreSQL user
  #password: "mypassword"
  
  # PostgresqlID is the ID of the PostgreSQL instance where this user should be created
  # This must match the postgresqlID in the Postgresql CRD
  # Example: "2BDAAA95-0465-473B-B270-E5503F1554FD"
  postgresqlID: "2BDAAA95-0465-473B-B270-E5503F1554FD"

