apiVersion: postgresql-operator.vyrodovalexey.github.com/v1alpha1
kind: User
metadata:
  labels:
    app.kubernetes.io/name: k8s-postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-wrong-postgresqlid
spec:
  # Username is the PostgreSQL username to create
  username: "myuser"
  
  # Regenerate password
  updatePassword: false
  
  # PostgresqlID is the ID of the PostgreSQL instance where this user should be created
  # This must match the postgresqlID in the Postgresql CRD
  # Example: "2BDAAA95-0465-473B-B270-E5503F1554FO"
  postgresqlID: "2BDAAA95-0465-473B-B270-E5503F1554FO"

